// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:a0ca4ae4-b02b-4045-be53-d2682b804ed1",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_wVGF38hsC",
    "aws_user_pools_web_client_id": "2ka6tlojnjbg1onl8ueh2019ei",
    "oauth": {
        "domain": "ichy98d3e1c0-98d3e1c0-stage.auth.us-east-2.amazoncognito.com",
        "scope": [
            "phone",
            "email",
            "openid",
            "profile",
            "aws.cognito.signin.user.admin"
        ],
        "redirectSignIn": "http://localhost:19002/",
        "redirectSignOut": "http://localhost:19002/",
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_POOLS"
};


export default awsmobile;
