// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:27c35d87-6fe2-47aa-90b9-aa6755f59cb8",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_HOEilnP2f",
    "aws_user_pools_web_client_id": "4rsrmgp03u4l2jlg28a3bvl7vv",
    "oauth": {
        "domain": "ichyappe0c6839b-e0c6839b-dev.auth.us-east-2.amazoncognito.com",
        "scope": [
            "phone",
            "email",
            "openid",
            "profile",
            "aws.cognito.signin.user.admin"
        ],
        "redirectSignIn": "http://localhost:19002/",
        "redirectSignOut": "http://localhost:19002/",
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_POOLS"
};


export default awsmobile;
